# development
server:
  # optional, default: 127.0.0.1
  host:
  # optional, default: 4000
  port:
  timezone: UTC
  cluster:  false
  base_url: http://127.0.0.1:4000/

db:
  db: cvl-dev
  # optional, default: localhost
  host:
  # optional, default: 27017
  port:
  # optional
  username:
  # optional
  password:

session:
  # optional, default: sessions
  collection:
  # change this to random string
  secret: 1234567890123456789012345678901234567890

logs:
  - sys
  - request
  - response
  - error
  - debug

libs:
  - albums

# libs that must run after server started
started: []

# admin panel password
password: whatever

mail:
  user:     someone@gmail.com
  password: passwords
  host:     smtp.gmail.com
  ssl:      true

aws:
  # your aws key & secret, those must not be empty if you set s3 option to true in assets config
  key:    12345678901234567890
  secret: 1234567890123456789012345678901234567890
  s3:
    bucket:  static.dev.coverline.com.tw
    postfix: .s3.amazonaws.com

static_host: http://static1.dev.coverline.com.tw
